#Hugo configuration
title = "deftones"
baseURL = "https:\/\/deftones.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
cookieDomain = "something.com"
